### PR TITLE
added reason to bean command

### PR DESCRIPTION
**Pull request by wrac4242**
Added an optional reason to the bean command

### CODE REVIEW

**Comment by stijnvdkolk** [comment]
@wrac4242 Can you fix the conflicts?

**Comment by wrac4242** [comment]
I think the issue is related to the switch to slash commands, so there is the potential it will be a few hourd

**Comment by wrac4242** [comment]
@stijnvdkolk fixed now

**Comment by wrac4242** [comment]
Found issue in the ordering of the if statement fixing now

**Review by stijnvdkolk — APPROVED** [review]

**Comment by promise** [comment]
lgtm

**Pull request merged**
